name = "MarketCycles"
uuid = "ac9b3a88-3e1f-57b7-8ce2-ad00cf637f7b"
authors = ["Andrew Bannerman <bannerman1985@gmail.com>"]
version = "0.0.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "^1.2"
DataFrames = ">=0.18.0"
CSV = ">=0.5.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
